<a href="https://colab.research.google.com/github/TechySanj/SyntheticData/blob/main/Generating_Syntheticdata(Faker).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
pip install Faker

Collecting Faker
  Downloading Faker-24.4.0-py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 9.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->Faker) (1.16.0)
Installing collected packages: Faker
Successfully installed Faker-24.4.0

In [4]:
import pandas as pd
from faker import Faker
import numpy as np

In [7]:
# Instantiate Faker object
fake = Faker()
Faker.seed(30) #Setting the seed allows you to re-generate the same fake data. Changing the seed will give you different randomly generated values.

In [8]:

# Create a DataFrame for employees
num_employees = 200
departments = ['Engineering', 'Finance', 'HR', 'Marketing', 'Sales', 'IT']

years_with_company = np.random.randint(1, 10, size=num_employees)
salary = 40000 + 2000 * years_with_company * np.random.randn()

In [9]:
employee_data = {
	'EmployeeID': np.arange(1, num_employees + 1),
	'FirstName': [fake.first_name() for _ in range(num_employees)],
	'LastName': [fake.last_name() for _ in range(num_employees)],
	'Age': np.random.randint(22, 60, size=num_employees),
	'Department': [fake.random_element(departments) for _ in range(num_employees)],
	'Salary': np.round(salary),
	'YearsWithCompany': years_with_company
}

df_employees = pd.DataFrame(employee_data)

# Display the head of the DataFrame
df_employees.head(10)

   EmployeeID FirstName   LastName  Age Department   Salary  YearsWithCompany
0           1     Amber   Williams   58    Finance  39290.0                 9
1           2     Keith       Kirk   37      Sales  39842.0                 2
2           3   Anthony    Schmidt   49  Marketing  39763.0                 3
3           4   Desiree    Parrish   24    Finance  39842.0                 2
4           5     Jason     Bowman   39    Finance  39290.0                 9
5           6  Jonathan      Mccoy   28    Finance  39369.0                 8
6           7     Randy  Rodriguez   40  Marketing  39290.0                 9
7           8   Darlene     Oliver   38         HR  39527.0                 6
8           9   Vanessa   Reynolds   32         HR  39921.0                 1
9          10    Steven       Hill   22         HR  39369.0                 8